### ISSUE TITLE
Play ID based off List.length does not work properly ...

### ISSUE THREAD

**Issue by sbditto85** [knowthen/elm#4]
If you create 2 plays:
- 1 player2 3pts
- 0 player1 3pts

then delete an old Play so it becomes
- 1 player2 3pts

then add a new play it becomes
- 1 player1 2pts
- 1 player2 3pts

which will mean if you delete or edit either of them then they both get edited. And this could be repeated so that eventually every play get edited/deleted.

Basically when delete is allowed the List.length for an ID generator doesn't work properly.

Normally in this case I keep a nextId in the model and increment it upon adding to the list.

**Comment by knowthen** [comment]
Yep, it's a bug for sure.  Your suggestion is a good one, however as this is just a simple prototype meant for learning the language.. And changing the source would require a lot of rerecording & editing of video, I'm going to leave it as is for now.  I don't think it takes away from the intended goals of the course.  Plus, in a real app this wouldn't be an issue, as you'd have an unique id from a database, which I'm sure you know. Thanks!

**Comment by sbditto85** [comment]
Maybe just put in an errata or comment about the bug so that others don't fall pray to the pitfall and know how to properly generate an ID if the database isn't feeding it.

I use elm in production and there are times where it isn't database driven and deletion is allowed so I feel it is definitely worth noting. 

PS can't wait for the next course, keep up the good work.

**Comment by knowthen** [comment]
Good thought, thanks for the kind words!

**Comment by simonwinklerzh** [comment]
Ah I see... Just came here to report the same issue.

I really enjoyed the course as well, perfect introduction to Elm!
